defaults:
  - bc@agent.bc_params
name: bcrl_sac
agent:
  _target_: agent.bcrl_sac.BCRLSACAgent.create
  lr: 1e-4
  hidden_dim: ${suite.hidden_dim}
  obs_spec: ???
  action_spec: ???
  pixel_keys: ${suite.pixel_keys}
  aux_keys: ${suite.aux_keys}
  critic_target_tau: 0.1
  repr_dim: ${suite.repr_dim}
  actor_type: 0
  critic_type: 0
  action_type: 0
  bc_snapshot_path:   /your_checkpoint

  use_layer_norm: true
  critic_dropout_rate: 0.0

  # SAC-specific parameters
  temperature_lr: 3e-4
  target_entropy: null  # Will use default -action_dim/2
  backup_entropy: true
  critic_ensemble_size: 5
  critic_subsample_size: 2
  temperature_init: 1.0

  bc_params:
    agent:
      obs_spec: null
      action_spec: null

irl: true
auto_rew_scale: true
load_rl: false
num_scale_estimation_episodes: 1
sinkhorn_rew_scale: 200
auto_rew_scale_factor: 4
utd_ratio: 16
min_reward: false

replay_buffer: ${suite.rl_replay_buffer}
pkg_path: ${root_dir}data/data.pkl
use_robot: true
